import numpy as np
from numpy import einsum

# The spin aaaa case.
doubles_res_aaaa = np.zeros()  # TODO
contracted_intermediate = -1.00 * einsum('kj,baik->abij', f_aa[oa, oa], t2_aaaa)
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('bc,caij->abij', f_aa[va, va], t2_aaaa)
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('kc,baik,cj->abij', f_aa[oa, va], t2_aaaa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('kc,caij,bk->abij', f_aa[oa, va], t2_aaaa, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
doubles_res_aaaa +=  1.00 * einsum('baij->abij', g_aaaa[va, va, oa, oa])
contracted_intermediate =  1.00 * einsum('kbij,ak->abij', g_aaaa[oa, va, oa, oa], t1_aa)
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('bacj,ci->abij', g_aaaa[va, va, va, oa], t1_aa)
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
doubles_res_aaaa +=  0.50 * einsum('lkij,balk->abij', g_aaaa[oa, oa, oa, oa], t2_aaaa)
contracted_intermediate =  1.00 * einsum('kbcj,caik->abij', g_aaaa[oa, va, va, oa], t2_aaaa)
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('bkjc,acik->abij', g_abab[va, ob, oa, vb], t2_abab)
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
doubles_res_aaaa +=  0.50 * einsum('bacd,cdij->abij', g_aaaa[va, va, va, va], t2_aaaa)
contracted_intermediate =  1.00 * einsum('lkcj,bail,ck->abij', g_aaaa[oa, oa, va, oa], t2_aaaa, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('lkjc,bail,ck->abij', g_abab[oa, ob, oa, vb], t2_aaaa, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  0.50 * einsum('lkcj,balk,ci->abij', g_aaaa[oa, oa, va, oa], t2_aaaa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('lkcj,cail,bk->abij', g_aaaa[oa, oa, va, oa], t2_aaaa, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('kljc,acil,bk->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('kbcd,daij,ck->abij', g_aaaa[oa, va, va, va], t2_aaaa, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('bkdc,daij,ck->abij', g_abab[va, ob, va, vb], t2_aaaa, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('kbcd,daik,cj->abij', g_aaaa[oa, va, va, va], t2_aaaa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('bkcd,adik,cj->abij', g_abab[va, ob, va, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate =  0.50 * einsum('kbcd,ak,cdij->abij', g_aaaa[oa, va, va, va], t1_aa, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
doubles_res_aaaa += -1.00 * einsum('lkij,al,bk->abij', g_aaaa[oa, oa, oa, oa], t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
contracted_intermediate =  1.00 * einsum('kbcj,ak,ci->abij', g_aaaa[oa, va, va, oa], t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
doubles_res_aaaa += -1.00 * einsum('bacd,cj,di->abij', g_aaaa[va, va, va, va], t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
contracted_intermediate = -0.50 * einsum('lkcd,bail,cdjk->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -0.50 * einsum('lkcd,bail,cdjk->abij', g_abab[oa, ob, va, vb], t2_aaaa, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -0.50 * einsum('lkdc,bail,dcjk->abij', g_abab[oa, ob, va, vb], t2_aaaa, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
doubles_res_aaaa +=  0.250 * einsum('lkcd,balk,cdij->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa += -0.50 * einsum('lkcd,daij,cblk->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa += -0.50 * einsum('lkdc,daij,bclk->abij', g_abab[oa, ob, va, vb], t2_aaaa, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_aaaa += -0.50 * einsum('kldc,daij,bckl->abij', g_abab[oa, ob, va, vb], t2_aaaa, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
contracted_intermediate =  1.00 * einsum('lkcd,dail,cbjk->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkdc,dail,bcjk->abij', g_abab[oa, ob, va, vb], t2_aaaa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('klcd,adil,cbjk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkcd,adil,bcjk->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
doubles_res_aaaa += -0.50 * einsum('lkcd,dalk,cbij->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  0.50 * einsum('lkcd,adlk,cbij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_aaaa +=  0.50 * einsum('klcd,adkl,cbij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
contracted_intermediate =  1.00 * einsum('lkcd,bail,ck,dj->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('lkdc,bail,ck,dj->abij', g_abab[oa, ob, va, vb], t2_aaaa, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkcd,daij,bl,ck->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, t1_aa, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('lkdc,daij,bl,ck->abij', g_abab[oa, ob, va, vb], t2_aaaa, t1_aa, t1_bb, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
doubles_res_aaaa += -0.50 * einsum('lkcd,balk,cj,di->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
contracted_intermediate =  1.00 * einsum('lkcd,dail,bk,cj->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('klcd,adil,bk,cj->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
doubles_res_aaaa += -0.50 * einsum('lkcd,al,bk,cdij->abij', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
contracted_intermediate = -1.00 * einsum('lkcj,al,bk,ci->abij', g_aaaa[oa, oa, va, oa], t1_aa, t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('kbcd,ak,cj,di->abij', g_aaaa[oa, va, va, va], t1_aa, t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_aaaa +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
doubles_res_aaaa +=  1.00 * einsum('lkcd,al,bk,cj,di->abij', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 3), (0, 2), (0, 1)])
# The spin aaab case.
doubles_res_aaab = np.zeros()  # TODO
# The spin aaba case.
doubles_res_aaba = np.zeros()  # TODO
# The spin aabb case.
doubles_res_aabb = np.zeros()  # TODO
# The spin abaa case.
doubles_res_abaa = np.zeros()  # TODO
# The spin abab case.
doubles_res_abab = np.zeros()  # TODO
doubles_res_abab +=  1.00 * einsum('kj,abik->abij', f_bb[ob, ob], t2_abab)
doubles_res_abab +=  1.00 * einsum('ki,abkj->abij', f_aa[oa, oa], t2_abab)
doubles_res_abab += -1.00 * einsum('bc,acij->abij', f_bb[vb, vb], t2_abab)
doubles_res_abab += -1.00 * einsum('ac,cbij->abij', f_aa[va, va], t2_abab)
doubles_res_abab +=  1.00 * einsum('kc,abik,cj->abij', f_bb[ob, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kc,abkj,ci->abij', f_aa[oa, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kc,acij,bk->abij', f_bb[ob, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kc,ak,cbij->abij', f_aa[oa, va], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -1.00 * einsum('abij->abij', g_abab[va, vb, oa, ob])
doubles_res_abab +=  1.00 * einsum('kbij,ak->abij', g_abab[oa, vb, oa, ob], t1_aa)
doubles_res_abab +=  1.00 * einsum('akij,bk->abij', g_abab[va, ob, oa, ob], t1_bb)
doubles_res_abab += -1.00 * einsum('abcj,ci->abij', g_abab[va, vb, va, ob], t1_aa)
doubles_res_abab += -1.00 * einsum('abic,cj->abij', g_abab[va, vb, oa, vb], t1_bb)
doubles_res_abab += -0.50 * einsum('lkij,ablk->abij', g_abab[oa, ob, oa, ob], t2_abab)
doubles_res_abab += -0.50 * einsum('klij,abkl->abij', g_abab[oa, ob, oa, ob], t2_abab)
doubles_res_abab +=  1.00 * einsum('kbcj,caik->abij', g_abab[oa, vb, va, ob], t2_aaaa)
doubles_res_abab += -1.00 * einsum('kbcj,acik->abij', g_bbbb[ob, vb, vb, ob], t2_abab)
doubles_res_abab +=  1.00 * einsum('akcj,cbik->abij', g_abab[va, ob, va, ob], t2_abab)
doubles_res_abab +=  1.00 * einsum('kbic,ackj->abij', g_abab[oa, vb, oa, vb], t2_abab)
doubles_res_abab += -1.00 * einsum('kaci,cbkj->abij', g_aaaa[oa, va, va, oa], t2_abab)
doubles_res_abab +=  1.00 * einsum('akic,cbjk->abij', g_abab[va, ob, oa, vb], t2_bbbb)
doubles_res_abab += -0.50 * einsum('abcd,cdij->abij', g_abab[va, vb, va, vb], t2_abab)
doubles_res_abab += -0.50 * einsum('abdc,dcij->abij', g_abab[va, vb, va, vb], t2_abab)
doubles_res_abab +=  1.00 * einsum('klcj,abil,ck->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcj,abil,ck->abij', g_bbbb[ob, ob, vb, ob], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkci,ablj,ck->abij', g_aaaa[oa, oa, va, oa], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('lkic,ablj,ck->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -0.50 * einsum('lkcj,ablk,ci->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -0.50 * einsum('klcj,abkl,ci->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -0.50 * einsum('lkic,ablk,cj->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -0.50 * einsum('klic,abkl,cj->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcj,cail,bk->abij', g_abab[oa, ob, va, ob], t2_aaaa, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('lkcj,acil,bk->abij', g_bbbb[ob, ob, vb, ob], t2_abab, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -1.00 * einsum('klcj,ak,cbil->abij', g_abab[oa, ob, va, ob], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkic,aclj,bk->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('lkci,ak,cblj->abij', g_aaaa[oa, oa, va, oa], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -1.00 * einsum('klic,ak,cbjl->abij', g_abab[oa, ob, oa, vb], t1_aa, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -1.00 * einsum('kbcd,adij,ck->abij', g_abab[oa, vb, va, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('kbcd,adij,ck->abij', g_bbbb[ob, vb, vb, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('kacd,dbij,ck->abij', g_aaaa[oa, va, va, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('akdc,dbij,ck->abij', g_abab[va, ob, va, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kbdc,daik,cj->abij', g_abab[oa, vb, va, vb], t2_aaaa, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kbcd,adik,cj->abij', g_bbbb[ob, vb, vb, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('akdc,dbik,cj->abij', g_abab[va, ob, va, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kbcd,adkj,ci->abij', g_abab[oa, vb, va, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kacd,dbkj,ci->abij', g_aaaa[oa, va, va, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('akcd,dbjk,ci->abij', g_abab[va, ob, va, vb], t2_bbbb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  0.50 * einsum('kbcd,ak,cdij->abij', g_abab[oa, vb, va, vb], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  0.50 * einsum('kbdc,ak,dcij->abij', g_abab[oa, vb, va, vb], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  0.50 * einsum('akcd,bk,cdij->abij', g_abab[va, ob, va, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  0.50 * einsum('akdc,bk,dcij->abij', g_abab[va, ob, va, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkij,al,bk->abij', g_abab[oa, ob, oa, ob], t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kbcj,ak,ci->abij', g_abab[oa, vb, va, ob], t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('akcj,bk,ci->abij', g_abab[va, ob, va, ob], t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kbic,ak,cj->abij', g_abab[oa, vb, oa, vb], t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('akic,bk,cj->abij', g_abab[va, ob, oa, vb], t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('abdc,cj,di->abij', g_abab[va, vb, va, vb], t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  0.50 * einsum('klcd,abil,cdkj->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  0.50 * einsum('kldc,abil,dckj->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  0.50 * einsum('lkcd,abil,cdjk->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  0.50 * einsum('lkcd,ablj,cdik->abij', g_aaaa[oa, oa, va, va], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  0.50 * einsum('lkcd,ablj,cdik->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  0.50 * einsum('lkdc,ablj,dcik->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -0.250 * einsum('lkcd,ablk,cdij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -0.250 * einsum('lkdc,ablk,dcij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -0.250 * einsum('klcd,abkl,cdij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -0.250 * einsum('kldc,abkl,dcij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  0.50 * einsum('lkcd,adij,cblk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  0.50 * einsum('klcd,adij,cbkl->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab +=  0.50 * einsum('lkcd,adij,cblk->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,dail,cbkj->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkdc,dail,cbjk->abij', g_abab[oa, ob, va, vb], t2_aaaa, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -1.00 * einsum('klcd,adil,cbkj->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,adil,cbjk->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,adlj,cbik->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab += -0.50 * einsum('lkcd,dalk,cbij->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  0.50 * einsum('lkcd,adlk,cbij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  0.50 * einsum('klcd,adkl,cbij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abab +=  1.00 * einsum('klcd,abil,ck,dj->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,abil,ck,dj->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,ablj,ck,di->abij', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('lkdc,ablj,ck,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('klcd,adij,bl,ck->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,adij,bl,ck->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,al,dbij,ck->abij', g_aaaa[oa, oa, va, va], t1_aa, t2_abab, t1_aa, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('lkdc,al,dbij,ck->abij', g_abab[oa, ob, va, vb], t1_aa, t2_abab, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abab += -0.50 * einsum('lkdc,ablk,cj,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_abab += -0.50 * einsum('kldc,abkl,cj,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkdc,dail,bk,cj->abij', g_abab[oa, ob, va, vb], t2_aaaa, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,adil,bk,cj->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('kldc,ak,dbil,cj->abij', g_abab[oa, ob, va, vb], t1_aa, t2_abab, t1_bb, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,adlj,bk,ci->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcd,ak,dblj,ci->abij', g_aaaa[oa, oa, va, va], t1_aa, t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('klcd,ak,dbjl,ci->abij', g_abab[oa, ob, va, vb], t1_aa, t2_bbbb, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_abab += -0.50 * einsum('lkcd,al,bk,cdij->abij', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t2_abab, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_abab += -0.50 * einsum('lkdc,al,bk,dcij->abij', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t2_abab, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkcj,al,bk,ci->abij', g_abab[oa, ob, va, ob], t1_aa, t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkic,al,bk,cj->abij', g_abab[oa, ob, oa, vb], t1_aa, t1_bb, t1_bb, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('kbdc,ak,cj,di->abij', g_abab[oa, vb, va, vb], t1_aa, t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_abab +=  1.00 * einsum('akdc,bk,cj,di->abij', g_abab[va, ob, va, vb], t1_bb, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_abab += -1.00 * einsum('lkdc,al,bk,cj,di->abij', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (1, 3), (0, 2), (0, 1)])
# The spin abba case.
doubles_res_abba = np.zeros()  # TODO
doubles_res_abba += -1.00 * einsum('kj,abki->abij', f_aa[oa, oa], t2_abab)
doubles_res_abba += -1.00 * einsum('ki,abjk->abij', f_bb[ob, ob], t2_abab)
doubles_res_abba +=  1.00 * einsum('bc,acji->abij', f_bb[vb, vb], t2_abab)
doubles_res_abba +=  1.00 * einsum('ac,cbji->abij', f_aa[va, va], t2_abab)
doubles_res_abba += -1.00 * einsum('kc,abki,cj->abij', f_aa[oa, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('kc,abjk,ci->abij', f_bb[ob, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('kc,acji,bk->abij', f_bb[ob, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('kc,ak,cbji->abij', f_aa[oa, va], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('abji->abij', g_abab[va, vb, oa, ob])
doubles_res_abba += -1.00 * einsum('kbji,ak->abij', g_abab[oa, vb, oa, ob], t1_aa)
doubles_res_abba += -1.00 * einsum('akji,bk->abij', g_abab[va, ob, oa, ob], t1_bb)
doubles_res_abba +=  1.00 * einsum('abjc,ci->abij', g_abab[va, vb, oa, vb], t1_bb)
doubles_res_abba +=  1.00 * einsum('abci,cj->abij', g_abab[va, vb, va, ob], t1_aa)
doubles_res_abba +=  0.50 * einsum('lkji,ablk->abij', g_abab[oa, ob, oa, ob], t2_abab)
doubles_res_abba +=  0.50 * einsum('klji,abkl->abij', g_abab[oa, ob, oa, ob], t2_abab)
doubles_res_abba += -1.00 * einsum('kbjc,acki->abij', g_abab[oa, vb, oa, vb], t2_abab)
doubles_res_abba +=  1.00 * einsum('kacj,cbki->abij', g_aaaa[oa, va, va, oa], t2_abab)
doubles_res_abba += -1.00 * einsum('akjc,cbik->abij', g_abab[va, ob, oa, vb], t2_bbbb)
doubles_res_abba += -1.00 * einsum('kbci,cajk->abij', g_abab[oa, vb, va, ob], t2_aaaa)
doubles_res_abba +=  1.00 * einsum('kbci,acjk->abij', g_bbbb[ob, vb, vb, ob], t2_abab)
doubles_res_abba += -1.00 * einsum('akci,cbjk->abij', g_abab[va, ob, va, ob], t2_abab)
doubles_res_abba +=  0.50 * einsum('abcd,cdji->abij', g_abab[va, vb, va, vb], t2_abab)
doubles_res_abba +=  0.50 * einsum('abdc,dcji->abij', g_abab[va, vb, va, vb], t2_abab)
doubles_res_abba +=  1.00 * einsum('lkcj,abli,ck->abij', g_aaaa[oa, oa, va, oa], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('lkjc,abli,ck->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('klci,abjl,ck->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkci,abjl,ck->abij', g_bbbb[ob, ob, vb, ob], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  0.50 * einsum('lkjc,ablk,ci->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  0.50 * einsum('kljc,abkl,ci->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  0.50 * einsum('lkci,ablk,cj->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  0.50 * einsum('klci,abkl,cj->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkjc,acli,bk->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('lkcj,ak,cbli->abij', g_aaaa[oa, oa, va, oa], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('kljc,ak,cbil->abij', g_abab[oa, ob, oa, vb], t1_aa, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkci,cajl,bk->abij', g_abab[oa, ob, va, ob], t2_aaaa, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('lkci,acjl,bk->abij', g_bbbb[ob, ob, vb, ob], t2_abab, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('klci,ak,cbjl->abij', g_abab[oa, ob, va, ob], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('kbcd,adji,ck->abij', g_abab[oa, vb, va, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('kbcd,adji,ck->abij', g_bbbb[ob, vb, vb, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('kacd,dbji,ck->abij', g_aaaa[oa, va, va, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('akdc,dbji,ck->abij', g_abab[va, ob, va, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('kbcd,adki,cj->abij', g_abab[oa, vb, va, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('kacd,dbki,cj->abij', g_aaaa[oa, va, va, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('akcd,dbik,cj->abij', g_abab[va, ob, va, vb], t2_bbbb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('kbdc,dajk,ci->abij', g_abab[oa, vb, va, vb], t2_aaaa, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('kbcd,adjk,ci->abij', g_bbbb[ob, vb, vb, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('akdc,dbjk,ci->abij', g_abab[va, ob, va, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('kbcd,ak,cdji->abij', g_abab[oa, vb, va, vb], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -0.50 * einsum('kbdc,ak,dcji->abij', g_abab[oa, vb, va, vb], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -0.50 * einsum('akcd,bk,cdji->abij', g_abab[va, ob, va, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('akdc,bk,dcji->abij', g_abab[va, ob, va, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkji,al,bk->abij', g_abab[oa, ob, oa, ob], t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('kbjc,ak,ci->abij', g_abab[oa, vb, oa, vb], t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('akjc,bk,ci->abij', g_abab[va, ob, oa, vb], t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('kbci,ak,cj->abij', g_abab[oa, vb, va, ob], t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -1.00 * einsum('akci,bk,cj->abij', g_abab[va, ob, va, ob], t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('abcd,cj,di->abij', g_abab[va, vb, va, vb], t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('lkcd,abli,cdjk->abij', g_aaaa[oa, oa, va, va], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('lkcd,abli,cdjk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('lkdc,abli,dcjk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('klcd,abjl,cdki->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('kldc,abjl,dcki->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('lkcd,abjl,cdik->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  0.250 * einsum('lkcd,ablk,cdji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  0.250 * einsum('lkdc,ablk,dcji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  0.250 * einsum('klcd,abkl,cdji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  0.250 * einsum('kldc,abkl,dcji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -0.50 * einsum('lkcd,adji,cblk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('klcd,adji,cbkl->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba += -0.50 * einsum('lkcd,adji,cblk->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,adli,cbjk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,dajl,cbki->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkdc,dajl,cbik->abij', g_abab[oa, ob, va, vb], t2_aaaa, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('klcd,adjl,cbki->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,adjl,cbik->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  0.50 * einsum('lkcd,dalk,cbji->abij', g_aaaa[oa, oa, va, va], t2_aaaa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -0.50 * einsum('lkcd,adlk,cbji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba += -0.50 * einsum('klcd,adkl,cbji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,abli,ck,dj->abij', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('lkdc,abli,ck,dj->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('klcd,abjl,ck,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,abjl,ck,di->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('klcd,adji,bl,ck->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,adji,bl,ck->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,al,dbji,ck->abij', g_aaaa[oa, oa, va, va], t1_aa, t2_abab, t1_aa, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('lkdc,al,dbji,ck->abij', g_abab[oa, ob, va, vb], t1_aa, t2_abab, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abba +=  0.50 * einsum('lkcd,ablk,cj,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abba +=  0.50 * einsum('klcd,abkl,cj,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,adli,bk,cj->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,ak,dbli,cj->abij', g_aaaa[oa, oa, va, va], t1_aa, t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('klcd,ak,dbil,cj->abij', g_abab[oa, ob, va, vb], t1_aa, t2_bbbb, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkdc,dajl,bk,ci->abij', g_abab[oa, ob, va, vb], t2_aaaa, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,adjl,bk,ci->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('kldc,ak,dbjl,ci->abij', g_abab[oa, ob, va, vb], t1_aa, t2_abab, t1_bb, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_abba +=  0.50 * einsum('lkcd,al,bk,cdji->abij', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t2_abab, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_abba +=  0.50 * einsum('lkdc,al,bk,dcji->abij', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t2_abab, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkjc,al,bk,ci->abij', g_abab[oa, ob, oa, vb], t1_aa, t1_bb, t1_bb, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkci,al,bk,cj->abij', g_abab[oa, ob, va, ob], t1_aa, t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('kbcd,ak,cj,di->abij', g_abab[oa, vb, va, vb], t1_aa, t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_abba += -1.00 * einsum('akcd,bk,cj,di->abij', g_abab[va, ob, va, vb], t1_bb, t1_aa, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_abba +=  1.00 * einsum('lkcd,al,bk,cj,di->abij', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (2, 3), (0, 2), (0, 1)])
# The spin abbb case.
doubles_res_abbb = np.zeros()  # TODO
# The spin baaa case.
doubles_res_baaa = np.zeros()  # TODO
# The spin baab case.
doubles_res_baab = np.zeros()  # TODO
doubles_res_baab += -1.00 * einsum('kj,baik->abij', f_bb[ob, ob], t2_abab)
doubles_res_baab += -1.00 * einsum('ki,bakj->abij', f_aa[oa, oa], t2_abab)
doubles_res_baab +=  1.00 * einsum('bc,caij->abij', f_aa[va, va], t2_abab)
doubles_res_baab +=  1.00 * einsum('ac,bcij->abij', f_bb[vb, vb], t2_abab)
doubles_res_baab += -1.00 * einsum('kc,baik,cj->abij', f_bb[ob, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('kc,bakj,ci->abij', f_aa[oa, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -1.00 * einsum('kc,caij,bk->abij', f_aa[oa, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('kc,ak,bcij->abij', f_bb[ob, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('baij->abij', g_abab[va, vb, oa, ob])
doubles_res_baab += -1.00 * einsum('bkij,ak->abij', g_abab[va, ob, oa, ob], t1_bb)
doubles_res_baab += -1.00 * einsum('kaij,bk->abij', g_abab[oa, vb, oa, ob], t1_aa)
doubles_res_baab +=  1.00 * einsum('bacj,ci->abij', g_abab[va, vb, va, ob], t1_aa)
doubles_res_baab +=  1.00 * einsum('baic,cj->abij', g_abab[va, vb, oa, vb], t1_bb)
doubles_res_baab +=  0.50 * einsum('lkij,balk->abij', g_abab[oa, ob, oa, ob], t2_abab)
doubles_res_baab +=  0.50 * einsum('klij,bakl->abij', g_abab[oa, ob, oa, ob], t2_abab)
doubles_res_baab += -1.00 * einsum('bkcj,caik->abij', g_abab[va, ob, va, ob], t2_abab)
doubles_res_baab += -1.00 * einsum('kacj,cbik->abij', g_abab[oa, vb, va, ob], t2_aaaa)
doubles_res_baab +=  1.00 * einsum('kacj,bcik->abij', g_bbbb[ob, vb, vb, ob], t2_abab)
doubles_res_baab +=  1.00 * einsum('kbci,cakj->abij', g_aaaa[oa, va, va, oa], t2_abab)
doubles_res_baab += -1.00 * einsum('bkic,cajk->abij', g_abab[va, ob, oa, vb], t2_bbbb)
doubles_res_baab += -1.00 * einsum('kaic,bckj->abij', g_abab[oa, vb, oa, vb], t2_abab)
doubles_res_baab +=  0.50 * einsum('bacd,cdij->abij', g_abab[va, vb, va, vb], t2_abab)
doubles_res_baab +=  0.50 * einsum('badc,dcij->abij', g_abab[va, vb, va, vb], t2_abab)
doubles_res_baab += -1.00 * einsum('klcj,bail,ck->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcj,bail,ck->abij', g_bbbb[ob, ob, vb, ob], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkci,balj,ck->abij', g_aaaa[oa, oa, va, oa], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('lkic,balj,ck->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  0.50 * einsum('lkcj,balk,ci->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  0.50 * einsum('klcj,bakl,ci->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  0.50 * einsum('lkic,balk,cj->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  0.50 * einsum('klic,bakl,cj->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('klcj,cail,bk->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcj,ak,cbil->abij', g_abab[oa, ob, va, ob], t1_bb, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('lkcj,ak,bcil->abij', g_bbbb[ob, ob, vb, ob], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('lkci,calj,bk->abij', g_aaaa[oa, oa, va, oa], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('klic,cajl,bk->abij', g_abab[oa, ob, oa, vb], t2_bbbb, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkic,ak,bclj->abij', g_abab[oa, ob, oa, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('kbcd,daij,ck->abij', g_aaaa[oa, va, va, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('bkdc,daij,ck->abij', g_abab[va, ob, va, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('kacd,bdij,ck->abij', g_abab[oa, vb, va, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('kacd,bdij,ck->abij', g_bbbb[ob, vb, vb, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('bkdc,daik,cj->abij', g_abab[va, ob, va, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('kadc,dbik,cj->abij', g_abab[oa, vb, va, vb], t2_aaaa, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('kacd,bdik,cj->abij', g_bbbb[ob, vb, vb, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('kbcd,dakj,ci->abij', g_aaaa[oa, va, va, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -1.00 * einsum('bkcd,dajk,ci->abij', g_abab[va, ob, va, vb], t2_bbbb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -1.00 * einsum('kacd,bdkj,ci->abij', g_abab[oa, vb, va, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -0.50 * einsum('bkcd,ak,cdij->abij', g_abab[va, ob, va, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -0.50 * einsum('bkdc,ak,dcij->abij', g_abab[va, ob, va, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -0.50 * einsum('kacd,bk,cdij->abij', g_abab[oa, vb, va, vb], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -0.50 * einsum('kadc,bk,dcij->abij', g_abab[oa, vb, va, vb], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  1.00 * einsum('klij,al,bk->abij', g_abab[oa, ob, oa, ob], t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('bkcj,ak,ci->abij', g_abab[va, ob, va, ob], t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -1.00 * einsum('kacj,bk,ci->abij', g_abab[oa, vb, va, ob], t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -1.00 * einsum('bkic,ak,cj->abij', g_abab[va, ob, oa, vb], t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('kaic,bk,cj->abij', g_abab[oa, vb, oa, vb], t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  1.00 * einsum('badc,cj,di->abij', g_abab[va, vb, va, vb], t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -0.50 * einsum('klcd,bail,cdkj->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -0.50 * einsum('kldc,bail,dckj->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -0.50 * einsum('lkcd,bail,cdjk->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -0.50 * einsum('lkcd,balj,cdik->abij', g_aaaa[oa, oa, va, va], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -0.50 * einsum('lkcd,balj,cdik->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -0.50 * einsum('lkdc,balj,dcik->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  0.250 * einsum('lkcd,balk,cdij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  0.250 * einsum('lkdc,balk,dcij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  0.250 * einsum('klcd,bakl,cdij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  0.250 * einsum('kldc,bakl,dcij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -0.50 * einsum('lkcd,daij,cblk->abij', g_aaaa[oa, oa, va, va], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -0.50 * einsum('lkdc,daij,bclk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab += -0.50 * einsum('kldc,daij,bckl->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('kldc,dail,bckj->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcd,dalj,cbik->abij', g_aaaa[oa, oa, va, va], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkdc,dalj,bcik->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  1.00 * einsum('klcd,dajl,cbik->abij', g_abab[oa, ob, va, vb], t2_bbbb, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcd,dajl,bcik->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -0.50 * einsum('lkdc,dalk,bcij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -0.50 * einsum('kldc,dakl,bcij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab +=  0.50 * einsum('lkcd,dalk,bcij->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baab += -1.00 * einsum('klcd,bail,ck,dj->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcd,bail,ck,dj->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcd,balj,ck,di->abij', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('lkdc,balj,ck,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcd,daij,bl,ck->abij', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, t1_aa, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('lkdc,daij,bl,ck->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('klcd,al,bdij,ck->abij', g_abab[oa, ob, va, vb], t1_bb, t2_abab, t1_aa, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcd,al,bdij,ck->abij', g_bbbb[ob, ob, vb, vb], t1_bb, t2_abab, t1_bb, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baab +=  0.50 * einsum('lkdc,balk,cj,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baab +=  0.50 * einsum('kldc,bakl,cj,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('kldc,dail,bk,cj->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkdc,ak,dbil,cj->abij', g_abab[oa, ob, va, vb], t1_bb, t2_aaaa, t1_bb, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcd,ak,bdil,cj->abij', g_bbbb[ob, ob, vb, vb], t1_bb, t2_abab, t1_bb, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcd,dalj,bk,ci->abij', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('klcd,dajl,bk,ci->abij', g_abab[oa, ob, va, vb], t2_bbbb, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('lkcd,ak,bdlj,ci->abij', g_abab[oa, ob, va, vb], t1_bb, t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baab +=  0.50 * einsum('klcd,al,bk,cdij->abij', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t2_abab, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baab +=  0.50 * einsum('kldc,al,bk,dcij->abij', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t2_abab, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('klcj,al,bk,ci->abij', g_abab[oa, ob, va, ob], t1_bb, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('klic,al,bk,cj->abij', g_abab[oa, ob, oa, vb], t1_bb, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('bkdc,ak,cj,di->abij', g_abab[va, ob, va, vb], t1_bb, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baab += -1.00 * einsum('kadc,bk,cj,di->abij', g_abab[oa, vb, va, vb], t1_aa, t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
doubles_res_baab +=  1.00 * einsum('kldc,al,bk,cj,di->abij', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (1, 3), (0, 2), (0, 1)])
# The spin baba case.
doubles_res_baba = np.zeros()  # TODO
doubles_res_baba +=  1.00 * einsum('kj,baki->abij', f_aa[oa, oa], t2_abab)
doubles_res_baba +=  1.00 * einsum('ki,bajk->abij', f_bb[ob, ob], t2_abab)
doubles_res_baba += -1.00 * einsum('bc,caji->abij', f_aa[va, va], t2_abab)
doubles_res_baba += -1.00 * einsum('ac,bcji->abij', f_bb[vb, vb], t2_abab)
doubles_res_baba +=  1.00 * einsum('kc,baki,cj->abij', f_aa[oa, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kc,bajk,ci->abij', f_bb[ob, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kc,caji,bk->abij', f_aa[oa, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kc,ak,bcji->abij', f_bb[ob, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('baji->abij', g_abab[va, vb, oa, ob])
doubles_res_baba +=  1.00 * einsum('bkji,ak->abij', g_abab[va, ob, oa, ob], t1_bb)
doubles_res_baba +=  1.00 * einsum('kaji,bk->abij', g_abab[oa, vb, oa, ob], t1_aa)
doubles_res_baba += -1.00 * einsum('bajc,ci->abij', g_abab[va, vb, oa, vb], t1_bb)
doubles_res_baba += -1.00 * einsum('baci,cj->abij', g_abab[va, vb, va, ob], t1_aa)
doubles_res_baba += -0.50 * einsum('lkji,balk->abij', g_abab[oa, ob, oa, ob], t2_abab)
doubles_res_baba += -0.50 * einsum('klji,bakl->abij', g_abab[oa, ob, oa, ob], t2_abab)
doubles_res_baba += -1.00 * einsum('kbcj,caki->abij', g_aaaa[oa, va, va, oa], t2_abab)
doubles_res_baba +=  1.00 * einsum('bkjc,caik->abij', g_abab[va, ob, oa, vb], t2_bbbb)
doubles_res_baba +=  1.00 * einsum('kajc,bcki->abij', g_abab[oa, vb, oa, vb], t2_abab)
doubles_res_baba +=  1.00 * einsum('bkci,cajk->abij', g_abab[va, ob, va, ob], t2_abab)
doubles_res_baba +=  1.00 * einsum('kaci,cbjk->abij', g_abab[oa, vb, va, ob], t2_aaaa)
doubles_res_baba += -1.00 * einsum('kaci,bcjk->abij', g_bbbb[ob, vb, vb, ob], t2_abab)
doubles_res_baba += -0.50 * einsum('bacd,cdji->abij', g_abab[va, vb, va, vb], t2_abab)
doubles_res_baba += -0.50 * einsum('badc,dcji->abij', g_abab[va, vb, va, vb], t2_abab)
doubles_res_baba += -1.00 * einsum('lkcj,bali,ck->abij', g_aaaa[oa, oa, va, oa], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('lkjc,bali,ck->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('klci,bajl,ck->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkci,bajl,ck->abij', g_bbbb[ob, ob, vb, ob], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -0.50 * einsum('lkjc,balk,ci->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -0.50 * einsum('kljc,bakl,ci->abij', g_abab[oa, ob, oa, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -0.50 * einsum('lkci,balk,cj->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -0.50 * einsum('klci,bakl,cj->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  1.00 * einsum('lkcj,cali,bk->abij', g_aaaa[oa, oa, va, oa], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('kljc,cail,bk->abij', g_abab[oa, ob, oa, vb], t2_bbbb, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkjc,ak,bcli->abij', g_abab[oa, ob, oa, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('klci,cajl,bk->abij', g_abab[oa, ob, va, ob], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkci,ak,cbjl->abij', g_abab[oa, ob, va, ob], t1_bb, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('lkci,ak,bcjl->abij', g_bbbb[ob, ob, vb, ob], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('kbcd,daji,ck->abij', g_aaaa[oa, va, va, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('bkdc,daji,ck->abij', g_abab[va, ob, va, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('kacd,bdji,ck->abij', g_abab[oa, vb, va, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('kacd,bdji,ck->abij', g_bbbb[ob, vb, vb, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kbcd,daki,cj->abij', g_aaaa[oa, va, va, va], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  1.00 * einsum('bkcd,daik,cj->abij', g_abab[va, ob, va, vb], t2_bbbb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kacd,bdki,cj->abij', g_abab[oa, vb, va, vb], t2_abab, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  1.00 * einsum('bkdc,dajk,ci->abij', g_abab[va, ob, va, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kadc,dbjk,ci->abij', g_abab[oa, vb, va, vb], t2_aaaa, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kacd,bdjk,ci->abij', g_bbbb[ob, vb, vb, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('bkcd,ak,cdji->abij', g_abab[va, ob, va, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('bkdc,ak,dcji->abij', g_abab[va, ob, va, vb], t1_bb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('kacd,bk,cdji->abij', g_abab[oa, vb, va, vb], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  0.50 * einsum('kadc,bk,dcji->abij', g_abab[oa, vb, va, vb], t1_aa, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -1.00 * einsum('klji,al,bk->abij', g_abab[oa, ob, oa, ob], t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('bkjc,ak,ci->abij', g_abab[va, ob, oa, vb], t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kajc,bk,ci->abij', g_abab[oa, vb, oa, vb], t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  1.00 * einsum('bkci,ak,cj->abij', g_abab[va, ob, va, ob], t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kaci,bk,cj->abij', g_abab[oa, vb, va, ob], t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -1.00 * einsum('bacd,cj,di->abij', g_abab[va, vb, va, vb], t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('lkcd,bali,cdjk->abij', g_aaaa[oa, oa, va, va], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('lkcd,bali,cdjk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('lkdc,bali,dcjk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('klcd,bajl,cdki->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('kldc,bajl,dcki->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('lkcd,bajl,cdik->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -0.250 * einsum('lkcd,balk,cdji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -0.250 * einsum('lkdc,balk,dcji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -0.250 * einsum('klcd,bakl,cdji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -0.250 * einsum('kldc,bakl,dcji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  0.50 * einsum('lkcd,daji,cblk->abij', g_aaaa[oa, oa, va, va], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('lkdc,daji,bclk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('kldc,daji,bckl->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkcd,dali,cbjk->abij', g_aaaa[oa, oa, va, va], t2_abab, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkdc,dali,bcjk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -1.00 * einsum('klcd,dail,cbjk->abij', g_abab[oa, ob, va, vb], t2_bbbb, t2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkcd,dail,bcjk->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -1.00 * einsum('kldc,dajl,bcki->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_baba +=  0.50 * einsum('lkdc,dalk,bcji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba +=  0.50 * einsum('kldc,dakl,bcji->abij', g_abab[oa, ob, va, vb], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -0.50 * einsum('lkcd,dalk,bcji->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkcd,bali,ck,dj->abij', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('lkdc,bali,ck,dj->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('klcd,bajl,ck,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkcd,bajl,ck,di->abij', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkcd,daji,bl,ck->abij', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, t1_aa, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('lkdc,daji,bl,ck->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('klcd,al,bdji,ck->abij', g_abab[oa, ob, va, vb], t1_bb, t2_abab, t1_aa, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkcd,al,bdji,ck->abij', g_bbbb[ob, ob, vb, vb], t1_bb, t2_abab, t1_bb, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baba += -0.50 * einsum('lkcd,balk,cj,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_baba += -0.50 * einsum('klcd,bakl,cj,di->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkcd,dali,bk,cj->abij', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('klcd,dail,bk,cj->abij', g_abab[oa, ob, va, vb], t2_bbbb, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkcd,ak,bdli,cj->abij', g_abab[oa, ob, va, vb], t1_bb, t2_abab, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('kldc,dajl,bk,ci->abij', g_abab[oa, ob, va, vb], t2_abab, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkdc,ak,dbjl,ci->abij', g_abab[oa, ob, va, vb], t1_bb, t2_aaaa, t1_bb, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('lkcd,ak,bdjl,ci->abij', g_bbbb[ob, ob, vb, vb], t1_bb, t2_abab, t1_bb, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
doubles_res_baba += -0.50 * einsum('klcd,al,bk,cdji->abij', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t2_abab, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baba += -0.50 * einsum('kldc,al,bk,dcji->abij', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t2_abab, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('kljc,al,bk,ci->abij', g_abab[oa, ob, oa, vb], t1_bb, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('klci,al,bk,cj->abij', g_abab[oa, ob, va, ob], t1_bb, t1_aa, t1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('bkcd,ak,cj,di->abij', g_abab[va, ob, va, vb], t1_bb, t1_aa, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_baba +=  1.00 * einsum('kacd,bk,cj,di->abij', g_abab[oa, vb, va, vb], t1_aa, t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
doubles_res_baba += -1.00 * einsum('klcd,al,bk,cj,di->abij', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (2, 3), (0, 2), (0, 1)])
# The spin babb case.
doubles_res_babb = np.zeros()  # TODO
# The spin bbaa case.
doubles_res_bbaa = np.zeros()  # TODO
# The spin bbab case.
doubles_res_bbab = np.zeros()  # TODO
# The spin bbba case.
doubles_res_bbba = np.zeros()  # TODO
# The spin bbbb case.
doubles_res_bbbb = np.zeros()  # TODO
contracted_intermediate = -1.00 * einsum('kj,baik->abij', f_bb[ob, ob], t2_bbbb)
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('bc,caij->abij', f_bb[vb, vb], t2_bbbb)
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('kc,baik,cj->abij', f_bb[ob, vb], t2_bbbb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('kc,caij,bk->abij', f_bb[ob, vb], t2_bbbb, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
doubles_res_bbbb +=  1.00 * einsum('baij->abij', g_bbbb[vb, vb, ob, ob])
contracted_intermediate =  1.00 * einsum('kbij,ak->abij', g_bbbb[ob, vb, ob, ob], t1_bb)
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('bacj,ci->abij', g_bbbb[vb, vb, vb, ob], t1_bb)
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
doubles_res_bbbb +=  0.50 * einsum('lkij,balk->abij', g_bbbb[ob, ob, ob, ob], t2_bbbb)
contracted_intermediate = -1.00 * einsum('kbcj,caki->abij', g_abab[oa, vb, va, ob], t2_abab)
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('kbcj,caik->abij', g_bbbb[ob, vb, vb, ob], t2_bbbb)
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
doubles_res_bbbb +=  0.50 * einsum('bacd,cdij->abij', g_bbbb[vb, vb, vb, vb], t2_bbbb)
contracted_intermediate = -1.00 * einsum('klcj,bail,ck->abij', g_abab[oa, ob, va, ob], t2_bbbb, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkcj,bail,ck->abij', g_bbbb[ob, ob, vb, ob], t2_bbbb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  0.50 * einsum('lkcj,balk,ci->abij', g_bbbb[ob, ob, vb, ob], t2_bbbb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkcj,cali,bk->abij', g_abab[oa, ob, va, ob], t2_abab, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('lkcj,cail,bk->abij', g_bbbb[ob, ob, vb, ob], t2_bbbb, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('kbcd,daij,ck->abij', g_abab[oa, vb, va, vb], t2_bbbb, t1_aa, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('kbcd,daij,ck->abij', g_bbbb[ob, vb, vb, vb], t2_bbbb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('kbdc,daki,cj->abij', g_abab[oa, vb, va, vb], t2_abab, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('kbcd,daik,cj->abij', g_bbbb[ob, vb, vb, vb], t2_bbbb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate =  0.50 * einsum('kbcd,ak,cdij->abij', g_bbbb[ob, vb, vb, vb], t1_bb, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
doubles_res_bbbb += -1.00 * einsum('lkij,al,bk->abij', g_bbbb[ob, ob, ob, ob], t1_bb, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
contracted_intermediate =  1.00 * einsum('kbcj,ak,ci->abij', g_bbbb[ob, vb, vb, ob], t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
doubles_res_bbbb += -1.00 * einsum('bacd,cj,di->abij', g_bbbb[vb, vb, vb, vb], t1_bb, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
contracted_intermediate = -0.50 * einsum('klcd,bail,cdkj->abij', g_abab[oa, ob, va, vb], t2_bbbb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -0.50 * einsum('kldc,bail,dckj->abij', g_abab[oa, ob, va, vb], t2_bbbb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -0.50 * einsum('lkcd,bail,cdjk->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
doubles_res_bbbb +=  0.250 * einsum('lkcd,balk,cdij->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb += -0.50 * einsum('lkcd,daij,cblk->abij', g_abab[oa, ob, va, vb], t2_bbbb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb += -0.50 * einsum('klcd,daij,cbkl->abij', g_abab[oa, ob, va, vb], t2_bbbb, t2_abab, optimize=['einsum_path', (0, 2), (0, 1)])
doubles_res_bbbb += -0.50 * einsum('lkcd,daij,cblk->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t2_bbbb, optimize=['einsum_path', (0, 2), (0, 1)])
contracted_intermediate =  1.00 * einsum('lkcd,dali,cbkj->abij', g_aaaa[oa, oa, va, va], t2_abab, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkdc,dali,cbjk->abij', g_abab[oa, ob, va, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('klcd,dail,cbkj->abij', g_abab[oa, ob, va, vb], t2_bbbb, t2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkcd,dail,cbjk->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
doubles_res_bbbb +=  0.50 * einsum('lkdc,dalk,cbij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_bbbb +=  0.50 * einsum('kldc,dakl,cbij->abij', g_abab[oa, ob, va, vb], t2_abab, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
doubles_res_bbbb += -0.50 * einsum('lkcd,dalk,cbij->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
contracted_intermediate = -1.00 * einsum('klcd,bail,ck,dj->abij', g_abab[oa, ob, va, vb], t2_bbbb, t1_aa, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkcd,bail,ck,dj->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('klcd,daij,bl,ck->abij', g_abab[oa, ob, va, vb], t2_bbbb, t1_bb, t1_aa, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkcd,daij,bl,ck->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
doubles_res_bbbb += -0.50 * einsum('lkcd,balk,cj,di->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
contracted_intermediate =  1.00 * einsum('lkdc,dali,bk,cj->abij', g_abab[oa, ob, va, vb], t2_abab, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
contracted_intermediate =  1.00 * einsum('lkcd,dail,bk,cj->abij', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
doubles_res_bbbb += -0.50 * einsum('lkcd,al,bk,cdij->abij', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, t2_bbbb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
contracted_intermediate = -1.00 * einsum('lkcj,al,bk,ci->abij', g_bbbb[ob, ob, vb, ob], t1_bb, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
contracted_intermediate = -1.00 * einsum('kbcd,ak,cj,di->abij', g_bbbb[ob, vb, vb, vb], t1_bb, t1_bb, t1_bb, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
doubles_res_bbbb +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
doubles_res_bbbb +=  1.00 * einsum('lkcd,al,bk,cj,di->abij', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, t1_bb, t1_bb, optimize=['einsum_path', (0, 3), (2, 3), (0, 2), (0, 1)])
