import numpy as np
from numpy import einsum

f_aa = np.zeros()
f_bb = np.zeros()
t1_aa = np.zeros()
t1_bb = np.zeros()
t2_aaaa = np.zeros()
t2_abab = np.zeros()
t2_bbbb = np.zeros()
g_aaaa = np.zeros()
g_abab = np.zeros()
g_bbbb = np.zeros()
oa = slice(0)
ob = slice(0)
va = slice(0)
vb = slice(0)

uhf_ccsd = np.zeros()  # TODO
uhf_ccsd +=  1.00 * einsum('ii', f_aa[oa, oa])
uhf_ccsd +=  1.00 * einsum('ii', f_bb[ob, ob])
uhf_ccsd +=  1.00 * einsum('ia,ai', f_aa[oa, va], t1_aa)
uhf_ccsd +=  1.00 * einsum('ia,ai', f_bb[ob, vb], t1_bb)
uhf_ccsd += -0.50 * einsum('jiji', g_aaaa[oa, oa, oa, oa])
uhf_ccsd += -0.50 * einsum('jiji', g_abab[oa, ob, oa, ob])
uhf_ccsd += -0.50 * einsum('ijij', g_abab[oa, ob, oa, ob])
uhf_ccsd += -0.50 * einsum('jiji', g_bbbb[ob, ob, ob, ob])
uhf_ccsd +=  0.250 * einsum('jiab,abji', g_aaaa[oa, oa, va, va], t2_aaaa)
uhf_ccsd +=  0.250 * einsum('jiab,abji', g_abab[oa, ob, va, vb], t2_abab)
uhf_ccsd +=  0.250 * einsum('ijab,abij', g_abab[oa, ob, va, vb], t2_abab)
uhf_ccsd +=  0.250 * einsum('jiba,baji', g_abab[oa, ob, va, vb], t2_abab)
uhf_ccsd +=  0.250 * einsum('ijba,baij', g_abab[oa, ob, va, vb], t2_abab)
uhf_ccsd +=  0.250 * einsum('jiab,abji', g_bbbb[ob, ob, vb, vb], t2_bbbb)
uhf_ccsd += -0.50 * einsum('jiab,ai,bj', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
uhf_ccsd +=  0.50 * einsum('ijab,ai,bj', g_abab[oa, ob, va, vb], t1_aa, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
uhf_ccsd +=  0.50 * einsum('jiba,ai,bj', g_abab[oa, ob, va, vb], t1_bb, t1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
uhf_ccsd += -0.50 * einsum('jiab,ai,bj', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
